root = "."

[build]
args_bin = []
bin = "./main"
pre_cmd = ["make build-tailwind", "make build-templ"]
cmd = "make build"
delay = 0
exclude_dir = ["public", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go", "._templ.go", "._tmpl.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 1000
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
