version: "3"

services:
  minio:
    container_name: codeflick-minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

    command: server --console-address ":9001" /data

    environment:
      MINIO_ROOT_USER: "HarshPatel"
      MINIO_ROOT_PASSWORD: "Password"

volumes:
  minio_data:
