version: "1.0"

services:
  codeflick_minio:
    container_name: codeflick-minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - minio-network
    environment:
      MINIO_ROOT_USER: "HarshPatel"
      MINIO_ROOT_PASSWORD: "Password"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: server --console-address ":9001" /data

  codeflick_postgres:
    container_name: codeflick-postgres
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "HarshPatel"
      POSTGRES_PASSWORD: "Password"
      POSTGRES_DB: "codeflick"
    volumes:
      - postgres_data:/data
    networks:
      - minio-network

volumes:
  minio_data:
  postgres_data:

networks:
  minio-network:
    driver: bridge
