services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - codeflick-network
    depends_on:
      codeflick_minio:
        condition: service_healthy
      codeflick_postgres:
        condition: service_healthy

  codeflick_minio:
    container_name: codeflick-minio
    # TO future harsh: we force version so we have current setup based on keys working.
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - codeflick-network
    environment:
      MINIO_ROOT_USER: "HarshPatel"
      MINIO_ROOT_PASSWORD: "Password"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: server --console-address ":9001" /data

  codeflick_postgres:
    container_name: codeflick-postgres
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data
    networks:
      - codeflick-network
    environment:
      POSTGRES_USER: "HarshPatel"
      POSTGRES_PASSWORD: "Password"
      POSTGRES_DB: "codeflick"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  minio_data:
  postgres_data:

networks:
  codeflick-network:
    driver: bridge
